site_name: ttt

nav:
  - Home: index.md
  - About: about.md
  - API reference:
    - Index: api/index.md
    - Engine: api/engine.md
    - Bits: api/bits.md

plugins:
  - search
  - macros:
      module_name: docs/macros
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            show_source: false
            # show_if_no_docstring: true
            # summary: true
            show_signature_annotations: true
            separate_signature: true
            line_length: 80
            show_root_heading: true
            group_by_category: true
            # show_category_heading: true
            show_symbol_type_heading: true
            heading_level: 2
            docstring_options:
              ignore_init_summary: true
            merge_init_into_class: true

theme:
  name: terminal
  custom_dir: docs/overrides
  palette: dark
  features:
    - footer.prev_next
    - style.links.underline.hide
    - navigation.side.indexes

extra_css:
  - style.css

markdown_extensions:
  # Python Markdown
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - meta
  - toc:
      permalink: "#"
      baselevel: 1
      toc_depth: 3

  # PyMdown Extensions
  - pymdownx.superfences
  - pymdownx.highlight:
      use_pygments: true
      pygments_style: github-dark
      noclasses: true
  - pymdownx.inlinehilite
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
