site_name: ttt
site_url: https://tenchi.team2xh.net/ttt/

nav:
  - Home: index.md
  - ttt:
    - Installation: ttt/install.md
    - Showcase: ttt/showcase.md
    - How does it work?: ttt/how.md
    - Art credits: ttt/art-credits.md
  - CLI reference:
    - Index: cli/index.md
    - Draw: cli/draw.md
    - Write: cli/write.md
    - List: cli/list.md
    - Frame: cli/frame.md
    - Watch: cli/watch.md
  - API reference:
    - Index: api/index.md
    - Engine: api/engine.md
    - Bits: api/bits.md
  - Lorem: lorem.md

hooks:
  - docs/patches.py

plugins:
  - search
  - macros:
      module_name: docs/macros
  - mkdocstrings:
      default_handler: python
      custom_templates: docs/overrides/mkdocstrings
      handlers:
        python:
          options:
            show_source: false
            # show_if_no_docstring: true
            # summary: true
            show_signature_annotations: true
            separate_signature: true
            line_length: 80
            show_root_heading: true
            group_by_category: true
            # show_category_heading: true
            show_symbol_type_heading: true
            heading_level: 2
            docstring_options:
              ignore_init_summary: true
            merge_init_into_class: true

theme:
  name: terminal
  custom_dir: docs/overrides/theme
  palette: dark
  features:
    - footer.prev_next
    - style.links.underline.hide
    - navigation.side.indexes

extra_css:
  - style.css

extra_javascript:
  - js/background.js
  - js/toc.js
  - js/title.js

markdown_extensions:
  # Python Markdown
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - meta
  - toc:
      permalink: "#"
      baselevel: 1
      toc_depth: 3

  # PyMdown Extensions
  - pymdownx.superfences
  - pymdownx.highlight:
      use_pygments: true
      pygments_style: monokai
      noclasses: true
  - pymdownx.inlinehilite
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde

  # Other
  - mkdocs-click
